import {useEffect,useMemo,useState} from 'react'
import {ArrowUpRight,ArrowDownRight,Target,PiggyBank,Lightbulb,CalendarRange,Wallet} from 'lucide-react'
import type {User} from '@supabase/supabase-js'
import type {Transaction} from './lib/data'
import {money} from './lib/data'
import {supabase} from './lib/supabase'

type Budget={id:string;category:string;amount:number;month:string}
type Goal={id:string;name:string;target_amount:number;saved_amount:number}
const localRead=<T,>(key:string):T[]=>{try{return JSON.parse(localStorage.getItem(key)||'[]') as T[]}catch{return []}}
const currentMonth=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const previousMonth=(key:string)=>{const [y,m]=key.split('-').map(Number);const d=new Date(y,m-2,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
const total=(items:Transaction[],month:string,type:'income'|'expense')=>items.filter(t=>t.date.startsWith(month)&&t.type===type).reduce((s,t)=>s+Number(t.amount),0)
const percent=(value:number,max:number)=>max>0?Math.min(100,Math.max(0,value/max*100)):0
function Delta({now,before,positiveWhenUp=true}:{now:number;before:number;positiveWhenUp?:boolean}){
 const delta=now-before,up=delta>0,good=positiveWhenUp?up:!up
 return <span className={`inline-flex items-center gap-1 text-xs font-semibold ${good?'text-[#59d8ac]':'text-[#f9ba69]'}`}>{delta===0?null:up?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {before===0?(now===0?'No change':'No prior-month baseline'):`${Math.abs(delta/before*100).toFixed(1)}%`} <span className="font-normal text-[#90a2b9]">{before===0&&now>0?'for comparison':'vs. last month'}</span></span>
}
export default function DashboardInsights({transactions,user,onNavigate}:{transactions:Transaction[];user:User|null;onNavigate:(v:'budgets'|'goals')=>void}){
 const [budgets,setBudgets]=useState<Budget[]>(()=>supabase?[]:localRead<Budget>('financeflow-v11-budgets'))
 const [goals,setGoals]=useState<Goal[]>(()=>supabase?[]:localRead<Goal>('financeflow-v11-goals'))
 const [loading,setLoading]=useState(!!supabase),[error,setError]=useState('')
 useEffect(()=>{if(!supabase){setBudgets(localRead('financeflow-v11-budgets'));setGoals(localRead('financeflow-v11-goals'));setLoading(false);return}if(!user){setBudgets([]);setGoals([]);setLoading(false);return}let active=true;setLoading(true);Promise.all([supabase.from('budgets').select('id,category,amount,month'),supabase.from('savings_goals').select('id,name,target_amount,saved_amount')]).then(([b,g])=>{if(!active)return;if(b.error||g.error)setError('Planning summaries could not load. Open Budgets or Savings Goals to check your connection.');else{setError('');setBudgets((b.data||[]) as Budget[]);setGoals((g.data||[]) as Goal[])}setLoading(false)}).catch(()=>{if(active){setError('Planning summaries are temporarily unavailable.');setLoading(false)}});return()=>{active=false}},[user])
 const stats=useMemo(()=>{const month=currentMonth(),last=previousMonth(month),income=total(transactions,month,'income'),expenses=total(transactions,month,'expense'),priorIncome=total(transactions,last,'income'),priorExpenses=total(transactions,last,'expense');const monthlyBudgets=budgets.filter(b=>b.month===month);const limit=monthlyBudgets.reduce((s,b)=>s+Number(b.amount),0);const budgetSpent=monthlyBudgets.reduce((s,b)=>s+transactions.filter(t=>t.type==='expense'&&t.category===b.category&&t.date.startsWith(month)).reduce((a,t)=>a+Number(t.amount),0),0);const saved=goals.reduce((s,g)=>s+Number(g.saved_amount),0),target=goals.reduce((s,g)=>s+Number(g.target_amount),0);const top=Object.entries(transactions.filter(t=>t.type==='expense'&&t.date.startsWith(month)).reduce<Record<string,number>>((a,t)=>({...a,[t.category]:(a[t.category]||0)+Number(t.amount)}),{})).sort((a,b)=>b[1]-a[1])[0];return{month,income,expenses,priorIncome,priorExpenses,limit,budgetSpent,saved,target,top,monthlyBudgets}},[transactions,budgets,goals])
 const alerts=stats.monthlyBudgets.map(b=>{const spent=transactions.filter(t=>t.type==='expense'&&t.category===b.category&&t.date.startsWith(stats.month)).reduce((sum,t)=>sum+Number(t.amount),0);const ratio=Number(b.amount)>0?spent/Number(b.amount):0;return {...b,spent,ratio}}).filter(b=>b.ratio>=.8).sort((a,b)=>b.ratio-a.ratio)
 const savingsRate=stats.income>0?(stats.income-stats.expenses)/stats.income*100:null
 return <section className="mb-5 space-y-5" aria-label="Monthly financial overview">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-[#55d8ac] text-[11px] font-bold uppercase tracking-[.18em]">Financial overview</p><h2 className="text-xl font-bold mt-1">Your monthly snapshot</h2></div><span className="pill px-3 py-2 text-xs flex gap-2 items-center"><CalendarRange size={15}/>{new Date(stats.month+'-01T12:00:00').toLocaleDateString('en-US',{month:'long',year:'numeric'})}</span></div>
  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
   <article className="card p-5"><p className="muted text-xs mb-3">This month's income</p><p className="text-2xl font-extrabold mb-3">{money(stats.income)}</p><Delta now={stats.income} before={stats.priorIncome}/></article>
   <article className="card p-5"><p className="muted text-xs mb-3">This month's expenses</p><p className="text-2xl font-extrabold mb-3">{money(stats.expenses)}</p><Delta now={stats.expenses} before={stats.priorExpenses} positiveWhenUp={false}/></article>
   <article className="card p-5"><p className="muted text-xs mb-3">Savings rate</p><p className="text-2xl font-extrabold mb-3">{savingsRate===null?'—':`${savingsRate.toFixed(1)}%`}</p><p className="text-xs muted">{savingsRate===null?'Add income this month to calculate':`${money(stats.income-stats.expenses)} net cash flow this month`}</p></article>
   <article className="card p-5"><div className="flex items-center justify-between"><p className="muted text-xs mb-3">All-time net balance</p><Wallet size={18} className="text-[#55d8ac]"/></div><p className="text-2xl font-extrabold mb-3">{money(transactions.reduce((s,t)=>s+(t.type==='income'?Number(t.amount):-Number(t.amount)),0))}</p><p className="text-xs muted">Income minus expenses across all records</p></article>
  </div>
  <div className="grid grid-cols-1 xl:grid-cols-2 gap-5">
   <article className="card p-5 md:p-6"><div className="flex justify-between gap-3 items-start"><div className="flex gap-3 items-center"><span className="p-2.5 rounded-xl bg-[#1b3d34] text-[#55d8ac]"><Target size={19}/></span><div><h3 className="font-bold">Monthly budget health</h3><p className="text-xs muted">Spending against your category limits</p></div></div><button className="text-xs text-[#55d8ac] hover:underline" onClick={()=>onNavigate('budgets')}>View budgets →</button></div>{loading?<p className="muted text-sm mt-7">Loading budgets…</p>:stats.monthlyBudgets.length?<><div className="flex justify-between items-end mt-7 mb-3"><span className="text-2xl font-extrabold">{money(stats.budgetSpent)} <span className="text-sm font-normal muted">spent</span></span><span className="text-sm muted">{money(stats.limit)} limit</span></div><div className="h-2.5 rounded-full bg-[#29384a] overflow-hidden"><div className={`h-full rounded-full ${stats.budgetSpent>stats.limit?'bg-[#f9ba69]':'bg-[#55d8ac]'}`} style={{width:`${percent(stats.budgetSpent,stats.limit)}%`}}/></div><p className="text-xs muted mt-3">{stats.budgetSpent>stats.limit?`${money(stats.budgetSpent-stats.limit)} over budget`:`${money(stats.limit-stats.budgetSpent)} remaining`} · {Math.round(stats.budgetSpent/stats.limit*100)}% used</p></>:<p className="muted text-sm mt-7">No budgets for this month. Create one to start tracking spending.</p>}</article>
   <article className="card p-5 md:p-6"><div className="flex justify-between gap-3 items-start"><div className="flex gap-3 items-center"><span className="p-2.5 rounded-xl bg-[#1c344a] text-[#70a7ff]"><PiggyBank size={19}/></span><div><h3 className="font-bold">Savings goals</h3><p className="text-xs muted">Progress toward what matters</p></div></div><button className="text-xs text-[#55d8ac] hover:underline" onClick={()=>onNavigate('goals')}>View goals →</button></div>{loading?<p className="muted text-sm mt-7">Loading goals…</p>:goals.length?<><div className="flex justify-between items-end mt-7 mb-3"><span className="text-2xl font-extrabold">{money(stats.saved)} <span className="text-sm font-normal muted">saved</span></span><span className="text-sm muted">{money(stats.target)} target</span></div><div className="h-2.5 rounded-full bg-[#29384a] overflow-hidden"><div className="h-full rounded-full bg-[#70a7ff]" style={{width:`${percent(stats.saved,stats.target)}%`}}/></div><p className="text-xs muted mt-3">{goals.length} active goal{goals.length!==1?'s':''} · {Math.round(percent(stats.saved,stats.target))}% complete</p></>:<p className="muted text-sm mt-7">No savings goals yet. Add one to see your progress here.</p>}</article>
  </div>
  {!loading&&alerts.length>0&&<div className="card p-5 md:p-6 border border-[#8a6239]" role="status"><h3 className="font-bold text-[#f9ba69] mb-3">Budget alerts</h3><div className="space-y-3">{alerts.map(b=><div key={b.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="font-semibold">{b.category} · {b.ratio>=1?'Limit reached or exceeded':'Approaching limit'}</span><span className="text-[#f9ba69]">{money(b.spent)} / {money(Number(b.amount))} ({Math.round(b.ratio*100)}%)</span></div>)}</div></div>}
  <article className="card p-5 md:p-6"><div className="flex items-center gap-2 mb-4"><Lightbulb size={19} className="text-[#f9ba69]"/><h3 className="font-bold">Your spending insights</h3></div>{error&&<p role="alert" className="text-sm text-[#f9ba69] mb-3">{error}</p>}<div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm"><div className="rounded-xl bg-[#172434] p-4"><p className="muted text-xs mb-2">Top expense category</p><p className="font-bold">{stats.top?stats.top[0]:'No spending yet'}</p><p className="text-xs muted mt-1">{stats.top?money(stats.top[1]):'Add an expense to see insights'}</p></div><div className="rounded-xl bg-[#172434] p-4"><p className="muted text-xs mb-2">Change in spending</p><p className="font-bold">{stats.priorExpenses===0?'No prior-month baseline':stats.expenses>stats.priorExpenses?'Spending increased':stats.expenses<stats.priorExpenses?'Spending decreased':'Spending unchanged'}</p><p className="text-xs muted mt-1">{stats.priorExpenses===0?'Add more monthly history':`${money(Math.abs(stats.expenses-stats.priorExpenses))} difference`}</p></div><div className="rounded-xl bg-[#172434] p-4"><p className="muted text-xs mb-2">Budget status</p><p className="font-bold">{stats.limit===0?'No budget set':alerts.some(b=>b.ratio>=1)?'Over budget':alerts.length?'Near budget limit':'On track'}</p><p className="text-xs muted mt-1">{stats.limit===0?'Create a monthly budget':`${stats.monthlyBudgets.length} categories tracked`}</p></div></div></article>
 </section>
}
