import {useMemo,useState} from 'react'
import type {ChangeEvent} from 'react'
import type {User} from '@supabase/supabase-js'
import {supabase} from './lib/supabase'
import {categories,incomeCategories,money} from './lib/data'
import type {Transaction} from './lib/data'
type Goal={id:string;name:string;target_amount:number;saved_amount:number}
// A matching date, title, category, type and amount is treated as a possible duplicate.
const fingerprint=(t:Pick<Transaction,'date'|'title'|'category'|'type'|'amount'>)=>JSON.stringify([t.date,t.title.trim().toLowerCase(),t.category,t.type,Math.round(Number(t.amount)*100)])
const parseCSV=(source:string)=>{const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field=''}else field+=c}if(quoted)throw Error('Unclosed CSV quote');row.push(field);if(row.some(x=>x.trim()))rows.push(row);return rows}
export default function Reports({items,user,onImport}:{items:Transaction[];user:User|null;onImport:(records:Transaction[])=>void}){
 const [preview,setPreview]=useState<Omit<Transaction,'id'>[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[monthlySaving,setMonthlySaving]=useState('100'),[goals,setGoals]=useState<Goal[]>([])
 const months=useMemo(()=>{const by=new Map<string,{income:number;expense:number}>();for(const t of items){const k=t.date.slice(0,7),v=by.get(k)||{income:0,expense:0};v[t.type]+=Number(t.amount);by.set(k,v)}return [...by].sort((a,b)=>b[0].localeCompare(a[0]))},[items])
 async function choose(e:ChangeEvent<HTMLInputElement>){setPreview([]);setError('');const f=e.target.files?.[0];if(!f)return;if(f.size>2_000_000){setError('CSV must be smaller than 2 MB');return}try{const rows=parseCSV(await f.text());const header=rows.shift()?.map(x=>x.trim().toLowerCase());if(!header||['date','title','category','type','amount'].some(h=>!header.includes(h)))throw Error('CSV requires Date, Title, Category, Type, Amount headers');if(rows.length>500)throw Error('Import up to 500 rows at once');const records=rows.map((r,i)=>{const val=(name:string)=>r[header.indexOf(name)]?.trim()||'';const type=val('type').toLowerCase();const amount=Number(val('amount'));const date=val('date');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(`${date}T00:00:00`))||!['income','expense'].includes(type)||!Number.isFinite(amount)||amount<=0||amount>1e9||!val('title')||val('title').length>120)throw Error(`Invalid data on CSV row ${i+2}`);const category=val('category');if(!(type==='income'?incomeCategories:categories).includes(category))throw Error(`Unsupported category on CSV row ${i+2}: ${category}`);return {date,title:val('title'),category,type:type as Transaction['type'],amount:Math.round(amount*100)/100}});const keys=new Set<string>();for(const record of records){const key=fingerprint(record);if(keys.has(key))throw Error('CSV contains identical transactions. Remove duplicate rows before importing.');keys.add(key)}setPreview(records)}catch(err){setError(String(err))}e.target.value=''}
 async function importData(){if(!preview.length||busy)return;setBusy(true);setError('');try{
  // Refresh cloud records before importing: this also detects a previously imported file.
  let existing=items;
  if(supabase){if(!user)throw Error('Sign in before importing transactions.');const cloudRecords:Transaction[]=[];for(let start=0;;start+=500){const {data,error}=await supabase.from('transactions').select('date,title,category,type,amount').range(start,start+499);if(error)throw error;cloudRecords.push(...((data??[]) as Transaction[]));if(!data||data.length<500)break}existing=cloudRecords}
  const known=new Set(existing.map(fingerprint));
  const duplicates=preview.filter(t=>known.has(fingerprint(t)));
  if(duplicates.length)throw Error(`${duplicates.length} transaction(s) already exist with matching date, title, category, type and amount. Import cancelled to prevent duplicates. Review your records before trying again.`);
  let added:Transaction[];
  if(supabase&&user){const {data,error}=await supabase.from('transactions').insert(preview.map(t=>({...t,user_id:user.id}))).select();if(error)throw error;added=data as Transaction[]}
  else added=preview.map(t=>({...t,id:crypto.randomUUID()}));
  onImport(added);setPreview([])
 }catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}
 async function loadGoals(){if(!supabase)return;const {data,error}=await supabase.from('savings_goals').select('id,name,target_amount,saved_amount');if(error)setError(error.message);else setGoals(data as Goal[])}
 return <div className="space-y-5"><div className="card p-6"><h2 className="text-xl font-bold">Monthly analytics</h2><p className="muted text-sm mt-2">Income, expenses, and net cash flow by month.</p><div className="overflow-x-auto mt-5"><table className="w-full text-sm text-left"><thead className="muted"><tr><th className="py-3">Month</th><th>Income</th><th>Expenses</th><th>Net</th></tr></thead><tbody>{months.map(([m,v])=><tr className="border-t border-[#263344]" key={m}><td className="py-3">{m}</td><td>{money(v.income)}</td><td>{money(v.expense)}</td><td>{money(v.income-v.expense)}</td></tr>)}</tbody></table>{!months.length&&<p className="muted text-sm">No transactions yet.</p>}</div></div><div className="card p-6"><h2 className="text-xl font-bold">Import transactions from CSV</h2><p className="muted text-sm mt-2">Use the FinanceFlow CSV export format: Date (YYYY-MM-DD), Title, Category, Type, Amount. Review the preview before importing. Matching transactions are checked before import. Identical legitimate transactions may require manual entry; concurrent imports still require server-side uniqueness for an absolute guarantee.</p><input className="field mt-4" aria-label="Choose CSV file" type="file" accept=".csv,text/csv" onChange={choose}/>{preview.length>0&&<div className="mt-4"><p className="text-sm">Ready to import {preview.length} transaction(s). First entry: {preview[0].title} ({money(preview[0].amount)}).</p><button className="btn-primary mt-3" disabled={busy} onClick={importData}>{busy?'Importing...':'Confirm import'}</button></div>}</div><div className="card p-6"><h2 className="text-xl font-bold">Savings projections</h2><p className="muted text-sm mt-2">Estimate completion based on a consistent monthly contribution. This is a projection, not a guarantee.</p><label className="block text-sm mt-4">Monthly contribution (USD)<input className="field mt-2 max-w-xs" type="number" min="0" step="0.01" value={monthlySaving} onChange={e=>setMonthlySaving(e.target.value)}/></label><button className="btn-outline mt-4" onClick={loadGoals}>Load cloud savings goals</button>{goals.map(g=>{const remaining=Math.max(0,g.target_amount-g.saved_amount),monthly=Number(monthlySaving),count=remaining===0?0:monthly>0?Math.ceil(remaining/monthly):null;return <div className="border-t border-[#263344] py-4 mt-4" key={g.id}><b>{g.name}</b><p className="muted text-sm">{money(g.saved_amount)} / {money(g.target_amount)} · {count===null?'Enter a positive monthly contribution':count===0?'Goal reached':`About ${count} month${count===1?'':'s'} remaining`}</p></div>})}{!supabase&&<p className="muted text-xs mt-3">Cloud goal projections require Supabase. Demo transactions and CSV tools remain available.</p>}</div>{error&&<p className="text-red-400 text-sm" role="alert">{error}</p>}</div>
}
